;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        beginning-of-buffer
        electric-newline-and-maybe-indent
        org-end-of-line
        org-self-insert-command
        org-yank
        smex
        ))

(setq mc/cmds-to-run-once
      '(
        undo-tree-visualize
        ))
