;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        beginning-of-buffer
        downcase-region
        electric-newline-and-maybe-indent
        end-of-buffer
        indent-for-tab-command
        kill-region
        org-end-of-line
        org-self-insert-command
        org-yank
        typescript-insert-and-indent
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        overwrite-mode
        smex
        undo-tree-visualize
        ))
